# Generated by Django 6.0.7 on 2026-08-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverApi', '0007_alter_driver_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbooking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
